name: Compile and Run index.tsx

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    env:
      GOOGLE_SHEET_API_KEY: ${{ secrets.GOOGLE_SHEET_API_KEY }}
      SHEET_ID: ${{ secrets.SHEET_ID }}
      WORDPRESS_URL: ${{ secrets.WORDPRESS_URL }}
      WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
      WORDPRESS_PASSWORD: ${{ secrets.WORDPRESS_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install --include=dev

      - name: Compile TypeScript
        run: npx tsc -p tsconfig.json

      - name: Run index.tsx
        run: node index.js